### ISSUE TITLE
Turns `awsgen` into a lein|boot task

### ISSUE THREAD

**Issue by cgrand** [portkey-cloud/aws-clj-sdk#7]

**Comment by viesti** [comment]
There's a Leiningen alias now, `lein gen-aws-api`.

https://github.com/portkey-cloud/aws-clj-sdk/blob/aeb414319a68e96bca09c48ac9633b974d03221d/project.clj#L12

**Comment by viesti** [comment]
Mental note: moving `awsgen.clj` to a dev time source path might be enough enough to close this issue (for Leiningen at least).

**Comment by viesti** [comment]
So wen't ahead and did this in d53de2d2b448b79398195ddaef13f967a4273671
