### ISSUE TITLE
Make a script to fetch json files from AWS official repos

### ISSUE THREAD

**Issue by cgrand** [portkey-cloud/aws-clj-sdk#8]
and move these son out of `resources`: they don't have to ship as part of the artifact.

**Comment by lvh** [comment]
As an alternative suggestion: have a development-time dependency on the aws `-models` artifact, which contains the relevant JSON files.

**Comment by viesti** [comment]
Thanks for the suggestion on `aws-java-sdk-models` @lvh! I made `generate-files!` to look for json files from this artifact and added it as dev time dependency.

**Comment by lvh** [comment]
Happy to help :) Once this project covers all the services, especially if I can get it without the specs, I hope to use it :) FWIW I'm doing tons of work with the AWS SDKs so if you're looking for an opinion or second set of eyes on something feel free to @ me :)
